name: "Release Helm Charts (No CR)"
description: "Automates Helm charts dependency updates, linting, packaging, and publishing using Github Pages"
author: "Rayen Dhmaied"
branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  charts_branch:
    description: "Branch to pull the Helm charts from"
    required: false
    default: "main"
  publish_branch:
    description: "Branch to push the Helm charts to"
    required: false
    default: "gh-pages"
  charts_dir:
    description: "Path to the Helm charts directory"
    required: false
    default: "helm-charts"
  helm_version:
    description: "Helm version to install"
    required: false
    default: "v3.12.0"
  token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: ${{ inputs.helm_version }}

    - name: Run Helm chart release script
      shell: bash
      env:
        CHARTS_BRANCH: ${{ inputs.charts_branch }}
        CHARTS_DIR: ${{ inputs.charts_dir }}
        PUBLISH_BRANCH: ${{ inputs.publish_branch }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REPO_NAME: ${{ github.event.repository.name }}
      run: |
        git clone -q --branch $CHARTS_BRANCH --single-branch https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git src
        git clone -q --branch $PUBLISH_BRANCH --single-branch https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git dest

        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

        ${{ github.action_path }}/release-helm-charts.sh
